###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: library2-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=library
        - MYSQL_DATABASE=library
        - MYSQL_USER=library
        - MYSQL_PASSWORD=library
      ports:
        - "8032:3306"

    webserver:
      image: nginx:alpine
      container_name: library2-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8030:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: library2-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

